import {
  DemoLead,
  DemoSurvey,
  DemoRABItem,
  DemoProject,
  DemoSPK,
  DemoMaterial,
  DemoTeamMember,
  DemoActivity,
} from './types';

export const SEED_LEADS: DemoLead[] = [
  {
    id: 'lead-1',
    name: 'Budi Santoso',
    phone: '0812-3456-7890',
    source: 'Website DINAMIS',
    projectType: 'Renovasi Rumah 2 Lantai',
    status: 'Survey',
    potentialValue: 150000000,
    notes: 'Ingin survei kondisi struktur lama dan perluasan dapur.',
    lastFollowUp: 'Hari ini, 09:30',
    createdAt: '2026-09-01',
  },
  {
    id: 'lead-2',
    name: 'Sari Property & Interior',
    phone: '0813-8899-2233',
    source: 'Rekomendasi Klien',
    projectType: 'Interior Kantor Creative Agency',
    status: 'RAB',
    potentialValue: 275000000,
    notes: 'Butuh partisi gypsum akustik dan meja custom 12 unit.',
    lastFollowUp: 'Kemarin, 14:15',
    createdAt: '2026-09-02',
  },
  {
    id: 'lead-3',
    name: 'Andi Wijaya',
    phone: '0818-5566-7788',
    source: 'Instagram Ads',
    projectType: 'Renovasi Dapur & Carport Minimalis',
    status: 'Lead Baru',
    potentialValue: 75000000,
    notes: 'Baru mengisi form, menunggu jadwal telepon perdana.',
    lastFollowUp: 'Hari ini, 08:00',
    createdAt: '2026-09-04',
  },
  {
    id: 'lead-4',
    name: 'Hendra Gunawan',
    phone: '0811-9988-1122',
    source: 'WhatsApp Referral',
    projectType: 'Renovasi Ruko Senayan 3 Lantai',
    status: 'Deal',
    potentialValue: 450000000,
    notes: 'SPK telah disepakati dan sudah masuk tahap survei detail.',
    lastFollowUp: '2 hari lalu',
    createdAt: '2026-08-28',
  },
];

export const SEED_PROJECTS: DemoProject[] = [
  {
    id: 'prj-1',
    title: 'Renovasi Ruko Senayan 3 Lantai',
    clientName: 'Hendra Gunawan',
    clientPhone: '0811-9988-1122',
    stage: 'Pengerjaan',
    contractValue: 450000000,
    rabBudget: 360000000,
    materialBudget: 195000000,
    startDate: '2026-09-01',
    targetEndDate: '2026-11-30',
    location: 'Jl. Senayan Utama No. 45, Jakarta Selatan',
    assignedMandor: 'Pak Budi (Mandor Utama)',
  },
  {
    id: 'prj-2',
    title: 'Fit-out Interior Kafe BSD',
    clientName: 'PT Artha Kuliner',
    clientPhone: '0812-7711-2299',
    stage: 'SPK',
    contractValue: 280000000,
    rabBudget: 220000000,
    materialBudget: 120000000,
    startDate: '2026-09-10',
    targetEndDate: '2026-10-25',
    location: 'Ruko BSD City Blok F-12, Tangerang Selatan',
    assignedMandor: 'Pak Joko (Mandor Finishing)',
  },
  {
    id: 'prj-3',
    title: 'Pembangunan Cluster Villa Ubud 2 Unit',
    clientName: 'I Made Sudarma',
    clientPhone: '0819-4455-6677',
    stage: 'Negosiasi',
    contractValue: 1450000000,
    rabBudget: 1180000000,
    materialBudget: 620000000,
    startDate: '2026-10-01',
    targetEndDate: '2027-03-31',
    location: 'Jl. Raya Sayan No. 88, Ubud, Bali',
    assignedMandor: 'Pak Wayan (Mandor Struktur)',
  },
];

export const SEED_SURVEYS: DemoSurvey[] = [
  {
    id: 'srv-1',
    leadId: 'lead-1',
    leadName: 'Budi Santoso',
    projectTitle: 'Renovasi Rumah 2 Lantai',
    date: '2026-09-05',
    locationAddress: 'Jl. Palagan Tentara Pelajar Km 9, Sleman, Yogyakarta',
    gpsCoords: '-7.7125, 110.3842 (Akurasi ±4m)',
    notes: 'Struktur pondasi lama masih kuat, perlu pembongkaran dinding pembatas ruang tamu.',
    status: 'Dijadwalkan',
  },
  {
    id: 'srv-2',
    leadId: 'lead-4',
    leadName: 'Hendra Gunawan',
    projectTitle: 'Renovasi Ruko Senayan 3 Lantai',
    date: '2026-08-30',
    locationAddress: 'Jl. Senayan Utama No. 45, Jakarta Selatan',
    gpsCoords: '-6.2255, 106.8001 (Akurasi ±3m)',
    notes: 'Pengecekan instalasi pipa plumbing dan kekuatan atap dak beton.',
    status: 'Selesai',
  },
];

export const SEED_RAB_ITEMS: DemoRABItem[] = [
  {
    id: 'rab-1',
    projectId: 'prj-1',
    category: 'Pekerjaan Struktur & Dinding',
    taskName: 'Pasangan Dinding Bata Ringan 10cm + Plester Aci',
    quantity: 145,
    unit: 'm²',
    unitPrice: 165000,
    subtotal: 23925000,
  },
  {
    id: 'rab-2',
    projectId: 'prj-1',
    category: 'Pekerjaan Plafon & Partisi',
    taskName: 'Plafon Gypsum Board 9mm Rangka Hollow Galvanis',
    quantity: 120,
    unit: 'm²',
    unitPrice: 140000,
    subtotal: 16800000,
  },
  {
    id: 'rab-3',
    projectId: 'prj-1',
    category: 'Pekerjaan Elektrikal',
    taskName: 'Instalasi Titik Lampu Downlight LED & Saklar Panasonic',
    quantity: 36,
    unit: 'Titik',
    unitPrice: 225000,
    subtotal: 8100000,
  },
  {
    id: 'rab-4',
    projectId: 'prj-1',
    category: 'Pekerjaan Lantai',
    taskName: 'Pemasangan Granit Tile 60x60cm Glazed Polish',
    quantity: 95,
    unit: 'm²',
    unitPrice: 285000,
    subtotal: 27075000,
  },
  {
    id: 'rab-5',
    projectId: 'prj-2',
    category: 'Interior & Finishing',
    taskName: 'Penyekat Kaca Tempered 10mm + Frame Aluminium Hitam',
    quantity: 24,
    unit: 'm²',
    unitPrice: 850000,
    subtotal: 20400000,
  },
];

export const SEED_SPK: DemoSPK[] = [
  {
    id: 'spk-1',
    projectId: 'prj-1',
    projectTitle: 'Renovasi Ruko Senayan 3 Lantai',
    clientName: 'Hendra Gunawan',
    contractValue: 450000000,
    downPayment: 135000000,
    startDate: '2026-09-01',
    targetEndDate: '2026-11-30',
    status: 'Aktif',
    spkNumber: 'SPK/DNM-CTR/2026/089',
  },
  {
    id: 'spk-2',
    projectId: 'prj-2',
    projectTitle: 'Fit-out Interior Kafe BSD',
    clientName: 'PT Artha Kuliner',
    contractValue: 280000000,
    downPayment: 84000000,
    startDate: '2026-09-10',
    targetEndDate: '2026-10-25',
    status: 'Menunggu Persetujuan',
    spkNumber: 'SPK/DNM-CTR/2026/092',
  },
];

export const SEED_MATERIALS: DemoMaterial[] = [
  {
    id: 'mat-1',
    projectId: 'prj-1',
    name: 'Semen Portland Gresik 50kg',
    category: 'Bahan Utama',
    quantity: 80,
    unit: 'Sak',
    estimatedCost: 65000,
    actualCost: 64000,
    supplier: 'TB Sumber Rejeki Senayan',
    status: 'Dibeli',
    purchaseDate: '2026-09-02',
  },
  {
    id: 'mat-2',
    projectId: 'prj-1',
    name: 'Besi Beton Ulir 12mm SNI',
    category: 'Bahan Struktur',
    quantity: 60,
    unit: 'Batang',
    estimatedCost: 110000,
    actualCost: 108000,
    supplier: 'Distributor Baja Sentosa',
    status: 'Dibeli',
    purchaseDate: '2026-09-02',
  },
  {
    id: 'mat-3',
    projectId: 'prj-1',
    name: 'Bata Ringan Hebel 10cm',
    category: 'Dinding',
    quantity: 14,
    unit: 'm³',
    estimatedCost: 720000,
    actualCost: 0,
    supplier: 'Depo Bangunan BSD',
    status: 'Menunggu',
  },
  {
    id: 'mat-4',
    projectId: 'prj-2',
    name: 'Hollow Galvanis 4x4 Tebal 0.7mm',
    category: 'Plafon & Partisi',
    quantity: 45,
    unit: 'Batang',
    estimatedCost: 38000,
    actualCost: 37500,
    supplier: 'TB Logam Makmur',
    status: 'Dibeli',
    purchaseDate: '2026-09-03',
  },
];

export const SEED_TEAM: DemoTeamMember[] = [
  {
    id: 'tm-1',
    name: 'Budi Raharjo',
    role: 'Mandor',
    phone: '0812-7788-9900',
    assignedProjectTitle: 'Renovasi Ruko Senayan 3 Lantai',
    dailyRate: 200000,
    status: 'Aktif di Proyek',
  },
  {
    id: 'tm-2',
    name: 'Andi Saputra',
    role: 'Tukang',
    phone: '0813-1122-3344',
    assignedProjectTitle: 'Renovasi Ruko Senayan 3 Lantai',
    dailyRate: 150000,
    status: 'Aktif di Proyek',
  },
  {
    id: 'tm-3',
    name: 'Joko Prabowo',
    role: 'Tukang',
    phone: '0815-6677-8899',
    assignedProjectTitle: 'Fit-out Interior Kafe BSD',
    dailyRate: 150000,
    status: 'Aktif di Proyek',
  },
  {
    id: 'tm-4',
    name: 'Rian Hidayat',
    role: 'Helper',
    phone: '0819-2233-4455',
    assignedProjectTitle: 'Renovasi Ruko Senayan 3 Lantai',
    dailyRate: 110000,
    status: 'Aktif di Proyek',
  },
  {
    id: 'tm-5',
    name: 'Wayan Sudarta',
    role: 'Supervisor',
    phone: '0812-4455-9988',
    assignedProjectTitle: 'Cluster Villa Ubud',
    dailyRate: 250000,
    status: 'Standby',
  },
];

export const SEED_ACTIVITIES: DemoActivity[] = [
  {
    id: 'act-1',
    timestamp: 'Hari ini, 10:30',
    title: 'Pencatatan Belanja Material',
    description: 'Besi Beton Ulir 12mm SNI (60 Batang) dicatat oleh Mandor Budi',
    category: 'material',
  },
  {
    id: 'act-2',
    timestamp: 'Hari ini, 09:45',
    title: 'Survei Proyek Baru Dijadwalkan',
    description: 'Survei lokasi untuk Budi Santoso (Renovasi Rumah 2 Lantai) dibuat',
    category: 'survey',
  },
  {
    id: 'act-3',
    timestamp: 'Kemarin, 16:20',
    title: 'RAB Proyek Diperbarui',
    description: 'Item pekerjaan granit tile ditambahkan ke proyek Ruko Senayan',
    category: 'rab',
  },
  {
    id: 'act-4',
    timestamp: 'Kemarin, 11:00',
    title: 'Tahap Proyek Berpindah',
    description: 'Proyek "Renovasi Ruko Senayan" resmi masuk tahap "Pengerjaan"',
    category: 'project',
  },
  {
    id: 'act-5',
    timestamp: '2 hari lalu',
    title: 'Lead Baru Masuk',
    description: 'Andi Wijaya (Renovasi Dapur) masuk via Instagram Ads',
    category: 'lead',
  },
];
