import {
  DemoLead,
  DemoFollowUp,
  DemoProduct,
  DemoDeal,
  DemoActivity,
} from './types';

export const SEED_PRODUCTS: DemoProduct[] = [
  {
    id: 'prod-1',
    name: 'Paket Starter Digital UMKM',
    category: 'Paket Solusi',
    price: 7500000,
    status: 'Aktif',
    description: 'Setup database pelanggan, integrasi broadcast pesan, dan SOP dasar follow-up tim sales.',
  },
  {
    id: 'prod-2',
    name: 'Paket Standard Business CRM',
    category: 'Software & Implementasi',
    price: 18500000,
    status: 'Aktif',
    description: 'Custom pipeline sales, reminder follow-up otomatis, training 3 admin, dan hak akses bertingkat.',
  },
  {
    id: 'prod-3',
    name: 'Jasa Optimasi Pipeline & Closing',
    category: 'Konsultasi & Training',
    price: 12000000,
    status: 'Aktif',
    description: 'Review alur sales, pembuatan script closing WhatsApp, dan audit rasio konversi leads.',
  },
  {
    id: 'prod-4',
    name: 'Paket Retainer Support Bulanan',
    category: 'Layanan Berlangganan',
    price: 3500000,
    status: 'Aktif',
    description: 'Pemeliharaan sistem berkala, update template pesan promosi, dan pendampingan mingguan.',
  },
  {
    id: 'prod-5',
    name: 'Integrasi Custom API & Dashboard',
    category: 'Solusi Khusus',
    price: 32000000,
    status: 'Aktif',
    description: 'Koneksi data penjualan multi-cabang dengan laporan otomatis rekap performa omset.',
  },
];

export const SEED_LEADS: DemoLead[] = [
  {
    id: 'lead-1',
    name: 'Bpk. Anton Nugroho',
    company: 'CV Sumber Makmur (Distributor Ritel)',
    phone: '0812-8899-1020',
    email: 'anton.sumbermakmur@gmail.com',
    source: 'WhatsApp',
    stage: 'Follow-up',
    interestProduct: 'Paket Standard Business CRM',
    potentialValue: 18500000,
    notes: 'Tertarik merapikan 5 sales lapangan yang sering lupa follow-up pelanggan toko kelontong.',
    lastContact: 'Hari ini, 09:30',
    nextFollowUpDate: '2026-09-04',
    createdAt: '2026-08-28',
  },
  {
    id: 'lead-2',
    name: 'Ibu Maya Septiani',
    company: 'Klinik Estetika Glow Beauty',
    phone: '0813-4455-6677',
    email: 'maya.glow@gmail.com',
    source: 'Instagram',
    stage: 'Negosiasi',
    interestProduct: 'Jasa Optimasi Pipeline & Closing',
    potentialValue: 12000000,
    notes: 'Butuh script follow-up reservasi treatment yang batal datang. Meminta termin 2 kali.',
    lastContact: 'Kemarin, 14:15',
    nextFollowUpDate: '2026-09-04',
    createdAt: '2026-08-25',
  },
  {
    id: 'lead-3',
    name: 'Bpk. David Kurniawan',
    company: 'PT Logistik Cepat Nusantara',
    phone: '0811-2233-4455',
    email: 'david@cepatnusantara.co.id',
    source: 'Google',
    stage: 'Deal',
    interestProduct: 'Integrasi Custom API & Dashboard',
    potentialValue: 32000000,
    notes: 'PO sudah disetujui Direksi. DP 50% sudah ditransfer kemarin sore.',
    lastContact: 'Hari ini, 08:00',
    nextFollowUpDate: '2026-09-08',
    createdAt: '2026-08-15',
  },
  {
    id: 'lead-4',
    name: 'Ibu Rina Handayani',
    company: 'Resto Dapur Nusantara (3 Cabang)',
    phone: '0819-7788-9900',
    email: 'rina.dapurnusantara@yahoo.com',
    source: 'Referral',
    stage: 'Lead Baru',
    interestProduct: 'Paket Starter Digital UMKM',
    potentialValue: 7500000,
    notes: 'Rekomendasi dari Bpk. Anton. Ingin sistem pencatatan pemesanan katering korporat.',
    lastContact: 'Hari ini, 10:00',
    nextFollowUpDate: '2026-09-05',
    createdAt: '2026-09-04',
  },
  {
    id: 'lead-5',
    name: 'Bpk. Hendra Wijaya',
    company: 'Toko Bahan Bangunan Sentosa',
    phone: '0857-1234-5678',
    email: 'hendra.sentosa@gmail.com',
    source: 'Facebook',
    stage: 'Dihubungi',
    interestProduct: 'Paket Standard Business CRM',
    potentialValue: 18500000,
    notes: 'Sudah dikirimkan PDF brosur ringkas via WhatsApp. Janji akan diskusi dengan partner toko.',
    lastContact: '3 hari lalu',
    nextFollowUpDate: '2026-09-02',
    createdAt: '2026-08-29',
  },
  {
    id: 'lead-6',
    name: 'Ibu Citra Lestari',
    company: 'Studio Foto Prisma Kreatif',
    phone: '0821-9988-7766',
    email: 'citra@prismastudio.id',
    source: 'Walk-in',
    stage: 'Deal',
    interestProduct: 'Paket Starter Digital UMKM',
    potentialValue: 7500000,
    notes: 'Sudah lunas paket starter. Sedang penjadwalan input data database 200 klien wedding.',
    lastContact: '2 hari lalu',
    createdAt: '2026-08-20',
  },
  {
    id: 'lead-7',
    name: 'Bpk. Reza Pratama',
    company: 'Agensi Digital Media Spark',
    phone: '0812-3344-5566',
    email: 'reza@mediaspark.id',
    source: 'Marketplace',
    stage: 'Tidak Jadi',
    interestProduct: 'Integrasi Custom API & Dashboard',
    potentialValue: 32000000,
    notes: 'Budget internal dialihkan untuk sewa kantor baru hingga kuartal depan.',
    lastContact: '1 minggu lalu',
    createdAt: '2026-08-10',
  },
];

export const SEED_FOLLOWUPS: DemoFollowUp[] = [
  {
    id: 'fu-1',
    leadId: 'lead-1',
    leadName: 'Bpk. Anton Nugroho',
    leadPhone: '0812-8899-1020',
    type: 'WhatsApp',
    dueDate: '2026-09-04',
    dueTime: '14:00',
    status: 'Pending',
    notes: 'Kirim revisi penawaran diskon paket 5 user sales lapangan CV Sumber Makmur.',
  },
  {
    id: 'fu-2',
    leadId: 'lead-2',
    leadName: 'Ibu Maya Septiani',
    leadPhone: '0813-4455-6677',
    type: 'Telepon',
    dueDate: '2026-09-04',
    dueTime: '16:30',
    status: 'Pending',
    notes: 'Konfirmasi draft kontrak termin 2 tahap untuk Klinik Estetika Glow.',
  },
  {
    id: 'fu-3',
    leadId: 'lead-5',
    leadName: 'Bpk. Hendra Wijaya',
    leadPhone: '0857-1234-5678',
    type: 'WhatsApp',
    dueDate: '2026-09-02',
    dueTime: '10:00',
    status: 'Terlambat',
    notes: 'Follow-up setelah pengiriman PDF brosur untuk Toko Bahan Bangunan Sentosa.',
  },
  {
    id: 'fu-4',
    leadId: 'lead-4',
    leadName: 'Ibu Rina Handayani',
    leadPhone: '0819-7788-9900',
    type: 'Meeting',
    dueDate: '2026-09-05',
    dueTime: '11:00',
    status: 'Pending',
    notes: 'Panggilan demo singkat alur pencatatan pesanan katering Dapur Nusantara via Google Meet.',
  },
  {
    id: 'fu-5',
    leadId: 'lead-3',
    leadName: 'Bpk. David Kurniawan',
    leadPhone: '0811-2233-4455',
    type: 'Kirim Penawaran',
    dueDate: '2026-08-30',
    status: 'Selesai',
    notes: 'Kirim invoice final & rekening perusahaan untuk pembayaran DP PT Logistik Cepat.',
    completedAt: '2026-08-30 15:45',
  },
  {
    id: 'fu-6',
    leadId: 'lead-6',
    leadName: 'Ibu Citra Lestari',
    leadPhone: '0821-9988-7766',
    type: 'WhatsApp',
    dueDate: '2026-08-22',
    status: 'Selesai',
    notes: 'Verifikasi bukti transfer pelunasan Paket Starter Studio Prisma.',
    completedAt: '2026-08-22 11:20',
  },
];

export const SEED_DEALS: DemoDeal[] = [
  {
    id: 'deal-1',
    leadId: 'lead-3',
    customerName: 'Bpk. David Kurniawan',
    customerCompany: 'PT Logistik Cepat Nusantara',
    productId: 'prod-5',
    productName: 'Integrasi Custom API & Dashboard',
    dealValue: 32000000,
    status: 'DP Diterima',
    dealDate: '2026-08-31',
    notes: 'DP 50% (Rp 16.000.000) telah terverifikasi. Pelunasan saat serah terima modul.',
  },
  {
    id: 'deal-2',
    leadId: 'lead-6',
    customerName: 'Ibu Citra Lestari',
    customerCompany: 'Studio Foto Prisma Kreatif',
    productId: 'prod-1',
    productName: 'Paket Starter Digital UMKM',
    dealValue: 7500000,
    status: 'Lunas',
    dealDate: '2026-08-22',
    notes: 'Pembayaran lunas via transfer BCA. Akses akun sudah diserahkan ke owner.',
  },
  {
    id: 'deal-3',
    leadId: 'lead-2',
    customerName: 'Ibu Maya Septiani',
    customerCompany: 'Klinik Estetika Glow Beauty',
    productId: 'prod-3',
    productName: 'Jasa Optimasi Pipeline & Closing',
    dealValue: 12000000,
    status: 'Menunggu Pembayaran',
    dealDate: '2026-09-03',
    notes: 'Invoice DP 50% sudah dikirimkan, menunggu eksekusi transfer dari tim finance klinik.',
  },
];

export const SEED_ACTIVITIES: DemoActivity[] = [
  {
    id: 'act-1',
    timestamp: 'Hari ini, 10:00',
    title: 'Lead Baru Masuk',
    description: 'Ibu Rina Handayani (Resto Dapur Nusantara) mendaftar dari Referral Bpk. Anton.',
    category: 'lead',
    leadId: 'lead-4',
  },
  {
    id: 'act-2',
    timestamp: 'Hari ini, 09:30',
    title: 'Follow-up Dijadwalkan',
    description: 'Jadwal follow-up revisi diskon penawaran untuk Bpk. Anton Nugroho (CV Sumber Makmur).',
    category: 'followup',
    leadId: 'lead-1',
  },
  {
    id: 'act-3',
    timestamp: 'Kemarin, 16:00',
    title: 'Deal Dibuat',
    description: 'Draft deal penawaran senilai Rp 12.000.000 dibuat untuk Ibu Maya (Klinik Estetika Glow).',
    category: 'deal',
    leadId: 'lead-2',
  },
  {
    id: 'act-4',
    timestamp: '31 Agu 2026',
    title: 'DP Deal Diterima',
    description: 'PT Logistik Cepat Nusantara melakukan transfer DP 50% senilai Rp 16.000.000.',
    category: 'deal',
    leadId: 'lead-3',
  },
  {
    id: 'act-5',
    timestamp: '29 Agu 2026',
    title: 'Tahap Pipeline Berubah',
    description: 'Bpk. Hendra Wijaya (Toko Bangunan Sentosa) dipindahkan ke tahap "Dihubungi".',
    category: 'pipeline',
    leadId: 'lead-5',
  },
];
